"""empty message

Revision ID: bdc1113cb7a4
Revises: 3e0775ab464d
Create Date: 2024-11-11 13:58:54.872430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc1113cb7a4'
down_revision: Union[str, None] = '3e0775ab464d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
